---
title: "SNACS"
output: html_document
---

```{r setup, include = FALSE}

## ------------------------------
```

```{r, echo = TRUE}
## ------------------------------
source("../src/processData.R")
source("../src/getBestSNPs.R")
source("../src/hashCall.R")
source("../src/createHeatmap.R")

## ------------------------------
## Parameters

verbose=FALSE

exptName="snacsExpt"
hashColors=c("green3","indianred2","dodgerblue3") ## optional

## ------------------------------
## Load data

load("example.RData")
dim(mutMat)
mutMat[1:4,1:4]
dim(hashMat)
hashMat[,1:4]

## ------------------------------
## Create SNACS object

snacsObj=SNACSList(mut=mutMat,hashes=hashMat,exptName=exptName,hashColors=hashColors)
snacsObj

names(snacsObj)
snacsObj$mut[1:4,1:4]
snacsObj$hashes[,1:4]
snacsObj$annHash

## Impute missing mutations

snacsObj=imputeMissingMutations(snacsObj=snacsObj,verbose=verbose)
snacsObj

## ------------------------------
## Cluster data to rank and select best SNPs
## Check heatmaps in "../output" folder

## P-value for selecting best SNPs
pvSnpThres=0.05

snacsObj=getBestSNPs(snacsObj,pvSnpThres=pvSnpThres)

## ------------------------------
## Make hash calls

## Parameters for making hash calls
prob_ecdf=0.95
propAboveBackground=0.5
probBackgndPeak=0.6
probBelowForeground=0.75

generateHashDensityPlot(snacsObj,prob_ecdf=prob_ecdf,probBackgndPeak=probBackgndPeak)

## Check hash density plots in "../output" folder

snacsObj=makeHashCall(snacsObj,prob_ecdf=prob_ecdf,probBackgndPeak=probBackgndPeak,probBelowForeground=probBelowForeground,propAboveBackground=propAboveBackground,minClustSize=10,clustComparePValue=10^-5)
snacsObj$annCell[1:4,]

## ------------------------------
## Create pretty heatmap

clustObj=createHeatmap(snacsObj,cell_anno_var=c(snacsObj$annHash$hashNames,"hashCall","clustRankedSNPs_hclust"),cell_anno_name=c(snacsObj$annHash$hashNames,"hash","rankedSNPsCluster"),col_dend=TRUE,row_dend=FALSE,outFormat="")

## ------------------------------
## Create heatmap in pdf format. All output files are saved in "../output" folder

clustObj=createHeatmap(snacsObj,cell_anno_var=c(snacsObj$annHash$hashNames,"hashCall","clustRankedSNPs_hclust"),cell_anno_name=c(snacsObj$annHash$hashNames,"hash","rankedSNPsCluster"),col_dend=TRUE,row_dend=FALSE,outputfileName=paste0("heatmap_pvBestWithAnn_",snacsObj$exptName),outFormat="pdf")
```

